### ISSUE TITLE
Data Entry for Gilliam County results

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-or#101]
OCR'ed files are in the [sources repo](https://github.com/openelections/openelections-sources-or/tree/master/Gilliam).

- [x] [2014 primary](http://www.co.gilliam.or.us/docs/election_5_20_2014_official_abstract.pdf)
- [x] [2012 general](http://www.co.gilliam.or.us/docs/2012_general_election_results.pdf)
- [x] [2010 general](http://www.co.gilliam.or.us/docs/election_11_2_2010_final_results.pdf)
- [x] [2010 primary](http://www.co.gilliam.or.us/docs/election_offical_results_May_18__2010.pdf)
- [x] 2008 general
- [x] 2008 primary
- [x] 2006 general
- [x] 2006 primary
- [x] 2004 general
- [x] 2004 primary
- [x] 2002 general
- [x] 2002 primary
- [x] 2000 general
- [x] 2000 primary

**Comment by nk9** [comment]
This total is incorrect.
`2012/20121106__or__general__gilliam__precinct.csv`
```
Gilliam,Prec #7,Secretary of State,,PGP,Seth Woolley,1
Gilliam,Prec #7,Secretary of State,,PRO,Robert Wolfe,1
Gilliam,Prec #7,Secretary of State,,LBT,Bruce Alexander Knight,7
Gilliam,Prec #7,Secretary of State,,DEM,Kate Brown,1501
Gilliam,Prec #7,Secretary of State,,REP,Knute Buehler,183
Gilliam,Prec #7,Secretary of State,,,Write-ins,1
Gilliam,Prec #7,Secretary of State,,,Total,343 <=======
Gilliam,Prec #7,Secretary of State,,,Over Votes,0
Gilliam,Prec #7,Secretary of State,,,Under Votes,15```

**Comment by dwillis** [comment]
Yep, got it. Was Kate Brown's total that was off (150 sted 1501).

**Comment by nk9** [comment]
I have also emailed these guys to get the decade of results before they got a website.

**Comment by nk9** [comment]
Good news from Gilliam!

> Good Morning,
>
> This is a great suggestion, thank you for your input we will take this into consideration, we have to go to storage and find these results, we will try to retrieve these records within the next couple of weeks.    
>
> Thank You
>>I am seeking precinct-level election results for the decade prior to 2010. I'm not concerned about special elections, just primaries and generals.
>>
>> Is this request something you can help me with? If you're able to come up with the 10 PDF files (or Excel spreadsheets?), perhaps you could just add those to the website so the public can have access to them. I'm happy to download them from there instead of dealing with large email attachments.
>>
>>I look forward to hearing back from you,
>>-Nick
