### ISSUE TITLE
Parse Lane County results

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-or#102]
Lane County precinct results are in HTML or text format and easily parseable, with a few quirks. We are interested in general and primary elections from [this page](http://www.lanecounty.org/Departments/CAO/Operations/CountyClerk/elections/Pages/HistoricalElectionResults.aspx) between 2000 and 2014:

- [x] [2016 primary](http://www.lanecounty.org/Departments/CAO/Operations/CountyClerk/elections/ElectionDocuments/20160517_Precinct.HTM)
- [x] [2014 general](http://www.lanecounty.org/Departments/CAO/Operations/CountyClerk/elections/ElectionDocuments/20141104_FinalCanvas.HTM)
- [x] [2014 primary](http://www.lanecounty.org/Departments/CAO/Operations/CountyClerk/elections/ElectionDocuments/20140520_FinalCanvas.HTM)
- [x] [2012 general](http://www.lanecounty.org/Departments/CAO/Operations/CountyClerk/elections/ElectionDocuments/20121106_SOV.txt)
- [x] 2012 primary
- [x] [2010 general](http://www.lanecounty.org/Departments/CAO/Operations/CountyClerk/elections/ElectionDocuments/20101102_SOV.txt)
- [x] [2010 primary](http://www.lanecounty.org/Departments/CAO/Operations/CountyClerk/elections/ElectionDocuments/20100518_SOV.txt)
- [x] [2008 general](http://www.lanecounty.org/Departments/CAO/Operations/CountyClerk/elections/ElectionDocuments/20081104s.txt)
- [x] [2008 primary](http://www.lanecounty.org/Departments/CAO/Operations/CountyClerk/elections/ElectionDocuments/20080520s.txt)
- [x] [2006 general](http://www.lanecounty.org/Departments/CAO/Operations/CountyClerk/elections/ElectionDocuments/20061107s.txt)
- [x] [2006 primary](http://www.lanecounty.org/Departments/CAO/Operations/CountyClerk/elections/ElectionDocuments/20060516s.txt)
- [x] [2004 general](http://www.lanecounty.org/Departments/CAO/Operations/CountyClerk/elections/ElectionDocuments/20041102s.txt)
- [x] [2004 primary](http://www.lanecounty.org/Departments/CAO/Operations/CountyClerk/elections/ElectionDocuments/20040518s.txt)
- [x] [2002 general](http://www.lanecounty.org/Departments/CAO/Operations/CountyClerk/elections/ElectionDocuments/20021105s.txt)
- [x] [2002 primary](http://www.lanecounty.org/Departments/CAO/Operations/CountyClerk/elections/ElectionDocuments/20020521s.txt)
- [x] [2000 general](http://www.lanecounty.org/Departments/CAO/Operations/CountyClerk/elections/ElectionDocuments/20001107s.txt)
- [x] [2000 primary](http://www.lanecounty.org/Departments/CAO/Operations/CountyClerk/elections/ElectionDocuments/20000516s.txt)

**Comment by nk9** [comment]
It looks to me like the [2008 general](http://www.lanecounty.org/Departments/CAO/Operations/CountyClerk/elections/ElectionDocuments/20081104s.txt) has the same format as the [2008 primary](http://www.lanecounty.org/Departments/CAO/Operations/CountyClerk/elections/ElectionDocuments/20080520s.txt). Since the general has already been parsed, does that mean there is already code somewhere that just needs a bit of tweaking?

I see `lane_parser.py` in the top level directory, but it is parsing the 2016 HTML file, not the text file format of the earlier precinct results.

**Comment by dwillis** [comment]
Hi @nk9: With Lane and some of the other counties, I would adapt each parser as I was going, so I'd just replace the bits that applied to each specific file and work from there.

**Comment by nk9** [comment]
Created a [pull request](https://github.com/openelections/openelections-data-or/pull/114) with 2008 primary results.

**Comment by dwillis** [comment]
The order is fine, @nk9 - thanks!

**Comment by nk9** [comment]
Found this tidbit on two pairs of precincts in Lane's 2004 general:

```* 421 ballots were counted in precinct 101215 that should have been counted in 
precinct 101223.  Same ballot styles, therefore no impact to contest results.
**144 ballots were counted in precinct 101315 that should have been counted in 
precinct 101313.  Same ballot styles, therefore no impact to contest results.```

What should I do about this? At present, the precinct names look like this:

```0053 3 EUGENE 313**
0054 5 EUGENE 315**```

**Comment by dwillis** [comment]
Let's do this: remove the asterisks in the precinct names, but add a notes column to the CSV (either programmatically or manually after the fact) and put those details in there for both sets of precincts. Does that work?

**Comment by nk9** [comment]
Sure thing. So, to be clear, this note will be repeated 172 times in the CSV? Should I continue to include a notes column in future CSVs?

**Comment by dwillis** [comment]
It's not ideal, but yeah, have it with each precinct result if that's doable. You don't have to include a notes column in future CSVs, but make a separate issue on this repository that includes your initial message and how you've handled it. Thanks!

**Comment by nk9** [comment]
I think this task is now complete.

**Comment by dwillis** [comment]
It is, at least until Lane certifies the 2016 general results!
