### ISSUE TITLE
Parse Hood River County results

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-or#104]
Election results are stored in PDFs (both electronic and image) ordered by precinct.
- [x] [2016 primary](http://www.co.hood-river.or.us/vertical/sites/%7B4BB5BFDA-3709-449E-9B16-B62A0A0DD6E4%7D/uploads/2016_May_precinct_level_abstract.pdf)
- [x] [2014 general](http://www.co.hood-river.or.us/vertical/sites/%7B4BB5BFDA-3709-449E-9B16-B62A0A0DD6E4%7D/uploads/November_4_2014_Official_Election_Results_by_Precinct.pdf)
- [x] [2014 primary](http://www.co.hood-river.or.us/vertical/sites/%7B4BB5BFDA-3709-449E-9B16-B62A0A0DD6E4%7D/uploads/May_20th_2014_Official_Election_Results_by_Precinct.pdf) (OCR needed)
- [x] [2012 general](http://www.co.hood-river.or.us/vertical/sites/%7B4BB5BFDA-3709-449E-9B16-B62A0A0DD6E4%7D/uploads/November_6th_2012_Official_Election_Results_by_Precinct%281%29.pdf)
- [x] 2012 primary
- [x] [2010 general](http://www.co.hood-river.or.us/vertical/sites/%7B4BB5BFDA-3709-449E-9B16-B62A0A0DD6E4%7D/uploads/%7B5160C1D4-F124-4C3D-95C9-BC8F031F781F%7D.PDF)
- [x] [2010 primary](http://www.co.hood-river.or.us/vertical/sites/%7B4BB5BFDA-3709-449E-9B16-B62A0A0DD6E4%7D/uploads/%7B36D38B14-C38A-49E9-869D-D8EF47D80B9A%7D.PDF)
- [x] [2008 general](http://www.co.hood-river.or.us/vertical/sites/%7B4BB5BFDA-3709-449E-9B16-B62A0A0DD6E4%7D/uploads/%7B3F141542-72AD-4260-B3DF-FCBCC6491801%7D.PDF)
- [x] [2008 primary](http://www.co.hood-river.or.us/vertical/sites/%7B4BB5BFDA-3709-449E-9B16-B62A0A0DD6E4%7D/uploads/%7BD592B8D7-A0A9-4A14-9D88-61AFC22E3533%7D.PDF)
- [x] [2006 general](http://www.co.hood-river.or.us/vertical/sites/%7B4BB5BFDA-3709-449E-9B16-B62A0A0DD6E4%7D/uploads/%7B994537BD-D029-4544-89B8-B6DDE4AB31E3%7D.PDF)
- [x] [2006 primary](https://github.com/openelections/openelections-sources-or/blob/master/Hood-River/20060516.pdf)
- [x] [2004 general](http://www.co.hood-river.or.us/vertical/sites/%7B4BB5BFDA-3709-449E-9B16-B62A0A0DD6E4%7D/uploads/%7BD00293FA-39E8-4342-93B2-DB75E8108E04%7D.PDF)
- [x] [2004 primary](https://github.com/openelections/openelections-sources-or/blob/master/Hood-River/20040518.pdf)
- [x] [2002 general](http://www.co.hood-river.or.us/vertical/sites/%7B4BB5BFDA-3709-449E-9B16-B62A0A0DD6E4%7D/uploads/%7B03C29741-EE96-4708-9157-692D857746F6%7D.PDF)
- [x] [2002 primary](https://github.com/openelections/openelections-sources-or/blob/master/Hood-River/20020521.pdf)
- [x] [2000 general](http://www.co.hood-river.or.us/vertical/sites/%7B4BB5BFDA-3709-449E-9B16-B62A0A0DD6E4%7D/uploads/%7B9CC2BFA4-B31B-44E9-9FE6-B7632EB4B214%7D.PDF)
- [x] [2000 primary](https://github.com/openelections/openelections-sources-or/blob/master/Hood-River/20000516.pdf)

**Comment by nk9** [comment]
The 2008 general PDF is so mangled it's not easily possible to tell which candidates ran for which offices. I've emailed to the county clerk to request the data in a usable format.

**Comment by dwillis** [comment]
@nk9 Yeah, that's a fun one. Thanks for your efforts.

**Comment by nk9** [comment]
Thanks for creating such a diverting and entertaining project!

Q: Page 13 of the 2008 primary PDF contains all the write-in candidates for GOP Attorney General. Should I list every name there in the results csv? I haven't seen the actual write-in names included in any other results so far.

**Comment by dwillis** [comment]
Thanks for helping! The answer is no, you don't have to itemize the
write-in votes; aggregates by precinct are fine.

**Comment by nk9** [comment]
I added the 2008 primary and 2006 general yesterday.

**Comment by nk9** [comment]
I've gotten the 2008 general results from the clerk. See my [pull request](https://github.com/openelections/openelections-sources-or/pull/3). One last file and this will be complete…

**Comment by nk9** [comment]
I requested the 4 missing primary elections and they sent them to me. Uploaded [here](https://github.com/openelections/openelections-sources-or/tree/master/Hood-River). Even better, they are real PDFs, not scans. So Tabula is going to work with no OCR scannos. We can add these to the checklist now.
