### ISSUE TITLE
Parse Jackson County results

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-or#107]
Will need OCR; precinct-level results are in multiple files.
- [x] [2014 general](http://jacksoncountyor.org/clerk/Elections/Election-Archives/ArtMID/5094/ArticleID/202397/General-Election-November-4-2014)
- [x] [2014 primary](http://jacksoncountyor.org/clerk/Elections/Election-Archives/ArtMID/5094/ArticleID/1177/Primary-Election-May-20-2014)
- [x] [2012 general](http://jacksoncountyor.org/clerk/Elections/Election-Archives/ArtMID/5094/ArticleID/1186/General-Election-November-6-2012)
- [x] [2010 general](http://jacksoncountyor.org/clerk/Elections/Election-Archives/ArtMID/5094/ArticleID/1192/General-Election-November-2-2010)
- [x] [2010 primary](http://jacksoncountyor.org/clerk/Elections/Election-Archives/ArtMID/5094/ArticleID/1193/Primary-Election-May-18-2010)
- [x] [2008 general](http://jacksoncountyor.org/clerk/Elections/Election-Archives/ArtMID/5094/ArticleID/1190/General-Election-November-4-2008)
- [x] [2008 primary](http://jacksoncountyor.org/clerk/Elections/Election-Archives/ArtMID/5094/ArticleID/1288/Primary-Election-May-20-2008)

**Comment by nk9** [comment]
I have done the 2008 general. The good news is that the county PDFs had actually already been OCRed. The bad news is that the scans weren't great, so there were tons of scannos. I used [OpenRefine](https://github.com/OpenRefine/OpenRefine) to clean up the data in bulk. It may be a good idea to mention that tool in the docs somewhere, as it's exactly what you need for this sort of work. There are some [good tutorials](https://github.com/sarahcnyt/data-journalism/tree/master/openrefine) about it around, too.
