### ISSUE TITLE
2016 Primary Election County files

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-or#113]
This is a place to track progress.
- [x] Baker
- [x] Benton
- [x] Clackamas
- [x] Clatsop
- [x] Columbia
- [x] Coos
- [x] Crook
- [x] Curry
- [x] Deschutes
- [x] Douglas
- [x] Gilliam
- [x] Grant
- [x] Harney
- [x] Hood River
- [x] Jackson
- [x] Jefferson
- [x] Josephine
- [x] Klamath
- [x] Lake
- [x] Lane
- [x] Lincoln
- [x] Linn
- [x] Malheur
- [x] Marion
- [x] Morrow
- [x] Multnomah
- [x] Polk
- [x] Sherman
- [x] Tillamook
- [x] Umatilla
- [x] Union
- [x] Wallowa
- [x] Wasco
- [x] Washington
- [x] Wheeler
- [x] Yamhill

**Comment by nk9** [comment]
Invalid number in Coos Sec State results:

```
⋊> ~/P/o/OR-data on master ⨯ python total_checksum.py 2016/20160517__or__primary__coos__precinct.csv
ERROR: Could not convert this to an integer: '0.33'
ERROR: {'': '', 'votes': '0.33', 'district': '', 'candidate': 'Under Votes', 'office': 'State Treasurer', 'county': 'Coos', 'party': 'REP', 'precinct': 'Precinct 15'}
```

**Comment by nk9** [comment]
Presumably Bud Pierce's precint is incorrect?

`2016/20160517__or__primary__wallowa__precinct.csv`
```
Wallowa,2,Governor,,REP,Bruce Cuff,20
Wallowa,2,Governor,,REP,Bob Niemeyer,16
Wallowa,2,Governor,,REP,Bob Forthan,5
Wallowa,1,Governor,,REP,Bud Pierce,82
Wallowa,2,Governor,,REP,Allen Alley,37
Wallowa,2,Governor,,REP,Write-in,0
Wallowa,2,Governor,,REP,Total,160
```

Also, this total doesn't add up:

```
Wallowa,7,State Treasurer,,DEM,Tobias Read,31
Wallowa,7,State Treasurer,,DEM,Write-in,1
Wallowa,7,State Treasurer,,DEM,Total,62
Wallowa,7,State Treasurer,,DEM,Over Votes,0
Wallowa,7,State Treasurer,,DEM,Under Votes,20
```

**Comment by dwillis** [comment]
Both of those fixed now, thanks!

**Comment by nk9** [comment]
The Lake County results are missing because the Lake website only has the general results, not the primary ones. I've emailed to ask them to fix the link.

**Comment by nk9** [comment]
Good news! Lake County primary results have come back from the OR SoS. Now in the [sources repo](https://github.com/openelections/openelections-sources-or/tree/master/Lake).

**Comment by dwillis** [comment]
That is awesome.
