### ISSUE TITLE
Josephine 2000 primary is unfinished

### ISSUE THREAD

**Issue by nk9** [openelections/openelections-data-or#131]
Here's the last line of the file:

`Josephine,Merlin 21,,,,,`

**Comment by dwillis** [comment]
Yeah, it's pretty clear from this that Josephine 2000 primary file isn't finished.

**Comment by nk9** [comment]
Completed in pull request #156.

**Comment by nk9** [comment]
Whoops, almost forgot: the B PDF is missing page 246, meaning most Dem results from precinct 36 are missing. I notice that many other pages are also omitted, presumably measures or local elected officials. Should we contact them about this and see of the missing page can be found?

**Comment by dwillis** [comment]
Yeah, that would be good.

**Comment by nk9** [comment]
Very fast turnaround for Josephine. I've got the missing page and have fixed the file.
