### ISSUE TITLE
Missing county files

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-or#143]
Attempting to track which precinct-level results files we don't have.

- [ ] 2016 Lake primary
- [ ] 2012 Crook primary
- [ ] 2010 Crook general
- [ ] 2010 Columbia primary
- [ ] 2008 Columbia general
- [ ] 2008 Gilliam general
- [ ] 2008 Grant general
- [x] 2008 Hood River general
- [ ] 2008 Linn general
- [ ] 2008 Malheur general
- [ ] 2008 Morrow general
- [x] 2008 Polk general
- [ ] 2008 Tillamook general
- [ ] 2006 Clackamas general
- [ ] 2006 Clackamas primary
- [ ] 2006 Clatsop primary

**Comment by nk9** [comment]
Crook county has responded:

> Unfortunately I do not have everything you are looking for.  The precinct level results that I have for the 3 noted below are in a spreadsheet format that does not have any certification from our office.  The only Certified Abstracts that I have are the summary results and they are not by precinct.  If you are interested in copies of what I have, the prices are listed below.  You may want to check with the Oregon Secretary of State’s office and see if they have any historic precinct level results for those older ones.  I am not sure if those were required to be sent in at that time….I am guessing that they were not because we do not have copies of them.
 >
>2012 primary - $7.35
2010 general - $6.55
2006 primary - $5.75
2004 general – not available
2004 primary – not available
2002 general – not available
2002 primary – not available
2000 general – not available
2000 primary – not available

I think it's worth snapping up the three she has, right?

**Comment by nk9** [comment]
Isn't the county matrix a better way to track this?

**Comment by dwillis** [comment]
Yeah, probably so.
