### ISSUE TITLE
Union 2016 primary has data that's different from certified results

### ISSUE THREAD

**Issue by nk9** [openelections/openelections-data-or#146]
The verifier is throwing up a bunch of errors in the Union 2016 primary file. In the course of fixing those, I discovered that the results are frequently a few votes low compared to the [official results](http://union-county.org/wp-content/uploads/2015/12/Union-County-Abstract.pdf) on the Union website. For example, this is in the file:

`Union,1,Attorney General,,REP,Bill Hansell,415`

but it should be this according to the PDF:

`Union,1,State Senate,29,REP,Bill Hansell,416`

Another strange thing is that the csv has a total column which agrees with the csv results, but is missing from the certified PDF. And of course, adjusting the results to match the PDF means that the totals need to be updated too.

The issue which led me to discover this is that the State Senate district 29 results are frequently mislabeled as being for Attorney General, for all parties.

I started fixing this by hand, but when I realized that the votes are wrong too, I figured it was best to flag this. I guess the data need to be reimported?

**Comment by dwillis** [comment]
Yep, I'll handle. Thanks!
