### ISSUE TITLE
Parse Lincoln county files

### ISSUE THREAD

**Issue by nk9** [openelections/openelections-data-or#159]
Lincoln county. Files are in the [sources repo](https://github.com/openelections/openelections-sources-or/tree/master/Lincoln), some need OCR.

- [x] 2014 general
- [x] 2014 primary
- [x] 2012 general
- [x] 2012 primary
- [x] 2010 general
- [x] 2010 primary
- [x] 2008 general
- [x] 2008 primary
- [x] 2006 general
- [x] 2006 primary
- [x] 2004 general
- [x] 2004 primary
- [x] 2002 general
- [x] 2002 primary
- [x] 2000 general
- [x] 2000 primary

**Comment by dwillis** [comment]
We have a volunteer working on the 2000-2004 files.
