### ISSUE TITLE
Parse 2012 Clatsop County primary precinct results

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-or#16]
Using Tabula, parse [this file](http://www.co.clatsop.or.us/sites/default/files/fileattachments/clerk_amp_elections/page/1429/5-15-12_final_official_canvass.pdf). Things to know:

* File name is 20120515__or__primary__clatsop__precinct.csv
* One row per candidate result, with these headers: precinct, office, district, party, candidate, votes.
* Use "State Senate" and "State House" for state legislative races, and "U.S. House" for House races, and be sure to include the district.
* Include "Over Votes" and "Under Votes" as "candidates" but skip other totals.

**Comment by ursulakaczmarek** [comment]
will send completed csv via gmail
