### ISSUE TITLE
Convert 2018 County Results

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-or#176]
Convert federal, statewide and state legislative race results into a CSV file from the [original PDF produced by the state](https://sos.oregon.gov/elections/Documents/results/november-2018-official-results.pdf).

The name of the CSV file should be: `20181106__or__general__county.csv`

We're interested in results for all federal and state offices, but if you want to generate files for the entire file, that's fine. The CSV files should have at least these fields: `county`, `office`, `district`, `party`, `candidate`, `votes`

We use Python and [Tabula](https://tabula.technology/) for the most part, but you can use whatever gets the job done, and we welcome contributions of parsers and other utilities.

**Comment by acolter** [comment]
I'll get started on this one.

**Comment by dwillis** [comment]
@acolter Thanks! I looked around and there's a WIP file on this that I've just pushed. It's up through the REP governor candidate.

**Comment by acolter** [comment]
Done. Sending the file your way.

**Comment by dwillis** [comment]
@acolter Thanks! Looks great.
