### ISSUE TITLE
2018 Lane County primary results

### ISSUE THREAD

**Issue by jheasly** [openelections/openelections-data-or#180]
There're vote `Total` rows in the results (157 instances). Would be happy to submit a fix, but just wanted to make sure before I did it that it needs doing, i.e., there isn't a workaround in the ingestion process or something like that.

**Comment by nk9** [comment]
Thanks for asking. They are there to allow [checksumming](https://github.com/openelections/openelections-data-or/blob/master/src/total_checksum.py) the various votes per precinct, etc.

**Comment by jheasly** [comment]
Re: [checksumming](https://github.com/openelections/openelections-data-or/blob/master/src/total_checksum.py) Neat! I'm an `argparse` newb. Much to learn from your example.  
Yeah, figured the Total is useful to have, but didn't see it in the example format nor in the one other county I randomly checked, so was just curious.  
Another thing I'm curious about; you don't happen to know if when @dwillis made the .csv he did it programmatically (w/ some post cleanup perhaps) or if he manually Tabula'd the 40-ish PDF pages that held the data?

**Comment by nk9** [comment]
Would be a good idea to have it in the example format. I wonder if that's just a bit out of date. It's easier in some states than others, though. Oregon is a very simple one compared to e.g. New York.

I don't know for sure how @dwillis did it this year, but I presume it was with Tabula from the [source files](https://github.com/openelections/openelections-sources-or/tree/master/Lane).

**Comment by dwillis** [comment]
@jheasly I dumped out the text (preserving the layout) using XPDF and then did some cleanup work on it.

**Comment by jheasly** [comment]
Interesting, thanks! I will check out XPDF.
