### ISSUE TITLE
2020 Primary County Results

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-or#195]
Convert federal, statewide and state legislative race results into a CSV file from the [original PDF produced by the state](https://sos.oregon.gov/elections/Documents/results/may-primary-2020.pdf).

The name of the CSV file should be: `20200519__or__primary__county.csv`

We're interested in results for all federal and state offices, but if you want to generate files for the entire file, that's fine. The CSV files should have at least these fields: `county`, `office`, `district`, `party`, `candidate`, `votes`

We use Python and [Tabula](https://tabula.technology/) for the most part, but you can use whatever gets the job done, and we welcome contributions of parsers and other utilities.

**Comment by zgordo** [comment]
I would like to work on this.
