### ISSUE TITLE
Convert 2000 General Election Statewide PDF with county-level results

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-or#2]
Using this [PDF file](http://sos.oregon.gov/elections/Documents/results/results-11-2000-statewide-offices.pdf), extract the information into a CSV file. 

Things to know:

* Output file is named 20001107__or__general__statewide.csv
* Headers should be: county, candidate, party, office, district, votes, incumbent.
* Each candidate results gets its own line.
* Incumbents are marked with an asterisk. Put TRUE in the incumbent column.
* For offices, use the district number as the district.
* Only include candidate totals, don't include overall totals.

**Comment by petehuang** [comment]
just to keep these issues updated: #1 and #2 have dead links

**Comment by dwillis** [comment]
Sigh. Thanks.
