### ISSUE TITLE
Parse 2012 Klamath County primary election results

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-or#21]
Using Tabula and [this file](http://www.klamathcounty.org/depts/clerk/results/2012/2012MayPrecinct.pdf) Things to know:

* File name is 20120515__or__primary__klamath__precinct.csv
* One row per candidate result, with these headers: precinct, office, district, party, candidate, votes.
* Use "State Senate" and "State House" for state legislative races, and "U.S. House" for House races, and be sure to include the district.
* Include "Over Votes" and "Under Votes" as "candidates" but skip other totals.

**Comment by ursulakaczmarek** [comment]
Will send csv via gmail.

**Comment by dwillis** [comment]
Hi @ursulakaczmarek - I just realized that I had this one basically done and finished it off. I'm sorry; can I ask if you're interested in doing another one?

**Comment by ursulakaczmarek** [comment]
Hi Derek-
Sure, I can start on #16, Clatsop County if that works for you.

**Comment by dwillis** [comment]
That would be great, thank you!
