### ISSUE TITLE
Parse 2012 Marion County primary election results

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-or#23]
Using Tabula and [this file](http://www.co.marion.or.us/NR/rdonlyres/8C51E1B2-BBA6-45DA-876E-3D0F959A49D2/42385/PrecinctReport.pdf). Things to know:

* File name is 20120515__or__primary__marion__precinct.csv
* One row per candidate result, with these headers: precinct, office, district, party, candidate, votes.
* You should skip the county commissioner races, which should make this pretty fast.
* Use "State Senate" and "State House" for state legislative races, and "U.S. House" for House races, and be sure to include the district.
* Include "Over Votes" and "Under Votes" as "candidates" but skip "votes cast."

**Comment by sckott** [comment]
taking a shot at this one if not already taken

**Comment by dwillis** [comment]
Have at it. Thanks!

**Comment by sckott** [comment]
hmmm, that's quite a large pdf (5000 pgs), trying https://github.com/tabulapdf/tabula-extractor but getting installation problems.  On `jruby -S gem install tabula-extractor` I get

```sh
SyntaxError: /Users/sacmac/.rbenv/shims/gem:3: syntax error, unexpected tSTRING_BEG
[ -n "$RBENV_DEBUG" ] && set -x
     ^
```

**Comment by sckott** [comment]
ah, i see, you said to skip commissioner races, that makes it faster

**Comment by dwillis** [comment]
I'll get started on this if you've gotten stuck (or want to switch to another task).

**Comment by sckott** [comment]
so sorry about this, just got stuck a while back and forgot about it, looks like you're already started https://github.com/openelections/openelections-data-or/blob/master/20120515__or__primary__marion__precinct.csv

**Comment by dwillis** [comment]
No worries - this one is kind of a pain, so I'm happy to tackle.
