### ISSUE TITLE
Parse Washington County 2012 primary election results

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-or#27]
Using [this file](http://www.co.washington.or.us/AssessmentTaxation/Elections/ElectionsArchive/upload/EL52.HTM)

* File name will be 20120515__or__primary__washington__precinct.csv
* One line for each candidate result.
* Use "State Senate" and "State House" for state legislative offices, and include districts for those and U.S. House office. 
* Include write-ins, over/under vote counts (list "Write-ins", "Over Votes" and "Under Votes" as the candidate).

**Comment by ursulakaczmarek** [comment]
I'll send the completed csv via gmail.
