### ISSUE TITLE
Parse 2012 Curry County general election results

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-or#30]
Using [this file](http://www.co.curry.or.us/Portals/0/Documents/clerk/11.06.12%20official%20final%20canvass.pdf). 

* File name will be 20121106__or__general__curry__precinct.csv
* One line for each candidate result.
* Use "State Senate" and "State House" for state legislative offices, and include districts for those and U.S. House office. 
* Include write-ins, over/under vote counts (list "Write-ins", "Over Votes" and "Under Votes" as the candidate).

**Comment by ursulakaczmarek** [comment]
I'll convert and send via gmail.

**Comment by dwillis** [comment]
:+1:
