### ISSUE TITLE
Data Entry of Precinct Results for Harney County

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-or#52]
Harney County has three precincts, so this isn't much work. The election results are [here](http://www.co.harney.or.us/past_election_results.html). There is no precinct-level file for 2008 primary.
- [x] 2014 general
- [x] 2014 primary
- [x] 2012 general
- [x] [2012 primary](https://github.com/openelections/openelections-data-or/blob/master/20120515__or__primary__harney__precinct.csv)
- [x] 2010 general
- [x] 2010 primary
- [x] 2008 general
- [x] 2006 general
- [x] 2006 primary
- [x] 2004 general
- [x] 2004 primary
- [x] 2002 general
- [x] 2002 primary
- [x] 2000 general
- [x] 2000 primary

**Comment by petehuang** [comment]
@dwillis think we're still missing 2004-2008 primary?

**Comment by dwillis** [comment]
You are correct, thanks!

**Comment by petehuang** [comment]
The 2008 primary doc doesn't have a precinct-level breakdown as far as I can tell.

**Comment by dwillis** [comment]
Looks like it, thanks.

**Comment by nk9** [comment]
The 2008 general file is actually the 2010 general results. Looks like 2008 needs to be done again. Hopefully the person who does this can divine the parties of the candidates from other counties' ballots.

**Comment by dwillis** [comment]
Good catch! I can grab that.

**Comment by nk9** [comment]
The Harney [website](http://www.co.harney.or.us/past_election_results.html) has the PDFs for all four primary/general elections in 2000 and 2000.

**Comment by nk9** [comment]
Wow, this is interesting. Pages 7 and 8 from the 2000 primary have the same contest, but different numbers. Page 8 says "RECOUNT" at the top, with a date of June 14th. I guess we should take the recount numbers?

**Comment by dwillis** [comment]
Finished 2002.
