### ISSUE TITLE
Data Entry of Wheeler County results

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-or#53]
Wheeler County has just three precincts, so this isn't too hard. Here are the [source files](https://github.com/openelections/openelections-sources-or/tree/master/Wheeler).

- [x] 2014 general
- [x] 2014 primary
- [x] 2012 general
- [x] [2012 primary](https://github.com/openelections/openelections-data-or/blob/master/20120515__or__primary__wheeler__precinct.csv)
- [x] 2010 general
- [x] 2010 primary
- [x] 2008 general
- [x] 2008 primary
- [x] 2006 general
- [x] 2006 primary
- [x] 2004 general
- [x] 2004 primary

**Comment by petehuang** [comment]
I'm looking to contribute here but I do have some questions. I noticed that the sample finished CSV on the readme only has partisan positions. The 2014 primary election results have non-partisan results as well (e.g. Wheeler County Assessor) and local measures. Do we include those?

**Comment by dwillis** [comment]
Thanks! We're only looking for partisan positions and for federal and state offices, including state legislature. No county or city offices.
