### ISSUE TITLE
Parse Clackamas County results

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-or#70]
Using Adobe Acrobat Pro, Tabula or xPDF for PDF results, or scraping for HTML. [Results here](https://github.com/openelections/openelections-sources-or/tree/master/Clackamas).
- [x] 2014 general
- [x] 2014 primary
- [x] 2012 general
- [x] 2012 primary
- [x] 2010 general
- [x] 2010 primary
- [x] 2008 general
- [x] 2008 primary
- [x] 2006 general
- [ ] ~~2006 primary~~
- [x] 2004 general
- [x] 2004 primary
- [x] 2002 general
- [x] 2002 primary
- [x] 2000 general
- [x] 2000 primary

**Comment by petehuang** [comment]
working on 2012 general

**Comment by dwillis** [comment]
:+1:

**Comment by petehuang** [comment]
2012 general should be in there; looking at 2008 general now!

**Comment by petehuang** [comment]
2004 and 2006 have neither primary nor general election results at the precinct level

**Comment by dwillis** [comment]
Right you are - updated the list.

**Comment by nk9** [comment]
Clackamas has a pretty straightforward [policy](http://www.clackamas.us/elections/pricelist.html) on prior election records.

> * Election Results*
> Statement of Votes Cast transferred to diskette - $.25 per race/measure or $5.00 for an entire election (whichever is less) plus $2.00 per diskette.

One would hope that they'd waive the diskette (?!?) fee if the results are emailed. We're missing 8 elections, so that's no more than $40.

**Comment by dwillis** [comment]
Let's go ahead and request, and I can either reimburse you or send money directly to the clerk.

**Comment by nk9** [comment]
I've made a request. We'll see what comes back.

**Comment by nk9** [comment]
I now have everything except the 2006 primary. They're still looking for that, apparently.

**Comment by dwillis** [comment]
@nk9 did you commit the earlier stuff you got from Clackamas? Do you need to be reimbursed for it?

**Comment by nk9** [comment]
Thanks for following up. Looks like I forgot to push this to the main repo after I got commit access. I've uploaded these and a few other bits and pieces I discovered lying around my hard drive. :-)

**Comment by acolter** [comment]
Working on 2006 general.

**Comment by acolter** [comment]
Working on 2002 general and primary.
