### ISSUE TITLE
Parse Douglas County results

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-or#73]
Using Tabula, xPDF or Acrobat Pro (most files will need OCR first). [Files here](http://www.co.douglas.or.us/clerk/election_results.asp) - use the "Abstracts" versions.
- [x] [2016 primary](http://www.co.douglas.or.us/clerk/election_results/election_20160517_abstract.pdf)
- [x] 2014 general (OCR first)
- [x] 2014 primary (OCR first)
- [x] 2012 general
- [x] 2012 primary
- [x] 2010 general (OCR first)
- [x] 2010 primary ([Dem](http://www.co.douglas.or.us/clerk/election_results/election_05182010_democrat.pdf) & [Rep](http://www.co.douglas.or.us/clerk/election_results/election_05182010_republican.pdf) abstracts, OCR first, can combine into single file)
- [x] [2008 general](http://www.co.douglas.or.us/clerk/election_results/election_11042008_abstract.pdf) (OCR first)
- [x] 2008 primary (OCR first)
- [x] 2006 general (OCR first)
- [x] 2006 primary (OCR first)
- [x] 2004 general (OCR first)
- [x] 2004 primary (OCR first)
- [x] 2002 general (OCR first)
- [x] 2002 primary (OCR first)
- [x] 2000 general (OCR first)
- [x] 2000 primary (OCR first)

**Comment by nk9** [comment]
County website seems to be down…

**Comment by dwillis** [comment]
@nk9 Looks like it's back up?

**Comment by nk9** [comment]
So strange. It's been unreachable for me every time I've tried for the past week. I'm in the UK, so perhaps that's why?

**Comment by dwillis** [comment]
That is odd. If it persists, I'll pull them down and add them openelections-sources-or repo.

**Comment by nk9** [comment]
Just a note to say that this is still happening. Having them on the github repo would be helpful. :-)

**Comment by dwillis** [comment]
I've added the pre-2008 general files to the sources repo.

**Comment by acolter** [comment]
Working on 2008 primary.
