### ISSUE TITLE
Parse Sherman County Results

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-or#75]
[Sherman](http://co.sherman.or.us/archive_of_election_results.asp) produces image PDFs, so these files will need to be OCRd before any parsing (or can be done by data entry since they are small):

- [x] [2014 general](http://co.sherman.or.us/documents/Clerk-GeneralElectionResults-November42014_000.pdf)
- [x] [2014 primary](http://co.sherman.or.us/documents/2014-05-20ShermanPrimaryAbstract.pdf)
- [x] [2012 general](http://co.sherman.or.us/documents/Clerk-2012GeneralElectionOfficialNationalResults11.06.12.pdf)
- [x] 2012 primary
- [x] [2010 general](http://co.sherman.or.us/documents/Clerk-2010ShermanGeneralElectionAbstract.pdf)
- [x] [2010 primary](http://co.sherman.or.us/documents/Clerk-May182010PrimaryElectionAbstract.pdf)
- [x] [2008 general](http://co.sherman.or.us/documents/Clerk-2008GeneralElectionAbstract.pdf)
- [x] 2008 primary
- [x] [2006 general](http://co.sherman.or.us/documents/Clerk-2006GeneralElectionAbstract.pdf)
- [x] 2006 primary
- [x] [2004 general](http://co.sherman.or.us/documents/Clerk-2004GeneralElectionfile1.pdf)
- [x] 2004 primary
- [x] [2002 general](http://co.sherman.or.us/documents/Clerk-2002GeneralElection.pdf)
- [x] 2002 primary

**Comment by petehuang** [comment]
surprisingly enough it seems like sherman county hasn't been on their game about renewing their domain...

**Comment by dwillis** [comment]
OMG

**Comment by dwillis** [comment]
Ok, switched to their other domain, so the links work now.

**Comment by dwillis** [comment]
Thanks!

**Comment by nk9** [comment]
I've emailed them to ask about the two 2000 elex we're missing.
