### ISSUE TITLE
Parse Yamhill County results

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-or#76]
Using Adobe Acrobat Pro, Tabula or xPDF for PDF results. [Results on the Yamhill website](http://www.co.yamhill.or.us/content/prior-year-elections) and also in [our sources repo](https://github.com/openelections/openelections-sources-or/blob/master/Yamhill/).
- [x] [2014 general](http://www.co.yamhill.or.us/sites/default/files/election-results/nov2014/generalelection/canvass.pdf)
- [x] [2014 primary](http://www.co.yamhill.or.us/sites/default/files/election-results/may2014/Canvass.pdf)
- [x] [2012 general](http://www.co.yamhill.or.us/sites/default/files/General_Election_Results_by_Precinct.pdf)
- [x] 2012 primary
- [x] [2010 general](http://www.co.yamhill.or.us/sites/default/files/Precinct_Results2010.pdf) - needs OCR
- [x] [2008 general](http://www.co.yamhill.or.us/sites/default/files/Nov4-08-canvass.pdf)
- [x] [2006 general](https://github.com/openelections/openelections-sources-or/blob/master/Yamhill/Nov%207%202006%20Election%20Results.pdf)
- [x] [2006 primary](https://github.com/openelections/openelections-sources-or/blob/master/Yamhill/20060516.pdf)
- [x] 2004 general
- [x] 2004 primary
- [x] [2002 general](https://github.com/openelections/openelections-sources-or/blob/master/Yamhill/20021105.pdf)
- [x] [2002 primary](https://github.com/openelections/openelections-sources-or/blob/master/Yamhill/20020521.pdf)
- [x] [2000 general](https://github.com/openelections/openelections-sources-or/blob/master/Yamhill/20001107.pdf)
- [x] [2000 primary](https://github.com/openelections/openelections-sources-or/blob/master/Yamhill/20000516.pdf)

**Comment by nk9** [comment]
Here are more official results for Yamhill:
* [2006 general](http://www.co.yamhill.or.us/sites/default/files/Nov%207%202006%20Election%20Results.pdf)
* 2004 general — [federal](http://web.archive.org/web/20061016185309/http://www.co.yamhill.or.us/clerk/elections_2004/20041102/documents/president%20and%20federal%20candidates.pdf), [state rep](http://web.archive.org/web/20061016185032/http://www.co.yamhill.or.us/clerk/elections_2004/20041102/documents/state%20rep%20candidates.pdf), [statewide offices](http://web.archive.org/web/20061016184944/http://www.co.yamhill.or.us/clerk/elections_2004/20041102/documents/statewide%20candidates.pdf), [state senate](http://web.archive.org/web/20061016185135/http://www.co.yamhill.or.us/clerk/elections_2004/20041102/documents/state%20senate%20candidates.pdf)
* 2004 primary — DEM [federal](http://web.archive.org/web/20061016185154/http://www.co.yamhill.or.us/clerk/elections_2004/20040518/documents/dem-fed_offices-pres_sen_rep.pdf), [state](http://web.archive.org/web/20061016184630/http://www.co.yamhill.or.us/clerk/elections_2004/20040518/documents/dem-state_offices.pdf) REP [federal](http://web.archive.org/web/20081214165008/http://www.co.yamhill.or.us/clerk/elections_2004/20040518/documents/rep-fed%20offices-pres,sen,rep.pdf), [state](http://web.archive.org/web/20081214165008/http://www.co.yamhill.or.us/clerk/elections_2004/20040518/documents/rep-state_offices.pdf)

**Comment by dwillis** [comment]
Grabbed these, thanks!

**Comment by nk9** [comment]
Sure! I just noticed, though, that the original issue description says that 2004 and 2006 results are available from the state website. So maybe that will be the best place to get them.

**Comment by dwillis** [comment]
I don't think that's true now (if it was true before).

**Comment by nk9** [comment]
Did you request results from Yamhill county for 2000 and 2002? Or are the "n/a"s just based on the results missing from their website?

**Comment by dwillis** [comment]
I didn't request 2000 and 2002, but they might have them: Gayle Jensen (jenseng@co.yamhill.or.us) was my contact. They charge for retrieval.

**Comment by nk9** [comment]
I've sent a request.

**Comment by nk9** [comment]
They've updated their website.

**Comment by acolter** [comment]
Working on 2006

**Comment by acolter** [comment]
Question about the 2000 primary results -- there are three sets of results for registered voters: Democrat, Republican, and Nonaffiliated Voters Voting Democrat. Should the totals for NAV Voting Democrat be added to the Democratic primary results?

**Comment by dwillis** [comment]
@acolter Oh, interesting. Hmm, I think I would not add them to the Democratic results, but have a separate party, something like `NAV-D`.
