### ISSUE TITLE
Parse Crook County Results

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-or#77]
[Crook County](https://github.com/openelections/openelections-sources-or/tree/master/Crook) has electronic PDFs that can be parsed using [Tabula](http://tabula.technology/), [xPDF](http://www.foolabs.com/xpdf/download.html) or Adobe Acrobat Pro. 
- [x] [2016 primary](https://github.com/openelections/openelections-sources-or/blob/master/Crook/2016%20May%20Primary%20Precinct%20Level%20Results.pdf)
- [x] 2014 general ([use this file as a model](https://github.com/openelections/openelections-data-or/blob/master/2014/20141104__or__general__crook__precinct.csv))
- [x] 2014 primary
- [x] 2012 primary
- [x] 2010 general
- [x] 2010 primary
- [x] 2008 general
- [x] 2008 primary
- [x] 2006 general
- [x] 2006 primary

**Comment by nk9** [comment]
Crook County has a [form](http://co.crook.or.us/Portals/0/ElectionDataOrder.pdf) to request back precinct-level elections results. Their fees are a bit confounding, though. I've emailed them to ask for some clarity.

**Comment by dwillis** [comment]
Crook charged us $25 per election, a flat fee. They did not have the 2010 general and 2012 primary files.

**Comment by nk9** [comment]
Ah, I see! Did they also not have anything prior to the 2006 general, or did you decide it wasn't worth the extra couple hundred dollars to get all the way back to 2000? :-)

**Comment by dwillis** [comment]
The did have reports prior to 2006 but I believe they would need to scan them first. But yeah, I didn't have the $400 it would have cost to go all the way back to 2000. I think we could do the remainder now, though.

**Comment by nk9** [comment]
Crook County has responded:

> Unfortunately I do not have everything you are looking for.  The precinct level results that I have for the 3 noted below are in a spreadsheet format that does not have any certification from our office.  The only Certified Abstracts that I have are the summary results and they are not by precinct.  If you are interested in copies of what I have, the prices are listed below.  You may want to check with the Oregon Secretary of State’s office and see if they have any historic precinct level results for those older ones.  I am not sure if those were required to be sent in at that time….I am guessing that they were not because we do not have copies of them.
 >
>2012 primary - $7.35
2010 general - $6.55
2006 primary - $5.75
2004 general – not available
2004 primary – not available
2002 general – not available
2002 primary – not available
2000 general – not available
2000 primary – not available

I think it's worth snapping up the three she has, right?

**Comment by dwillis** [comment]
Yes, definitely. I can send them a check for those.

**Comment by nk9** [comment]
Alright, I'll respond to the email and CC you saying to expect a check shortly. (y)

**Comment by nk9** [comment]
The files have arrived!
