### ISSUE TITLE
Parse Washington County results

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-or#79]
[Washington County](http://www.co.washington.or.us/AssessmentTaxation/Elections/ElectionsArchive/index.cfm) has electronic PDFs that can be parsed using [Tabula](http://tabula.technology/), [xPDF](http://www.foolabs.com/xpdf/download.html) or Adobe Acrobat Pro. The 2011 file is HTML. [Here is](https://github.com/openelections/openelections-data-or/blob/master/20120515__or__primary__washington__precinct.csv) what a finished CSV file looks like.

- [x] [2016 primary](http://www.co.washington.or.us/AssessmentTaxation/Elections/CurrentElection/upload/Amended-Statement-of-Votes-Cast-by-Contests-May-2016-Primary-Election.pdf)
- [x] [2014 general](http://www.co.washington.or.us/AssessmentTaxation/Elections/upload/November-2014-Precinct-Abstract.pdf)
- [x] [2014 primary](http://www.co.washington.or.us/AssessmentTaxation/Elections/ElectionsArchive/upload/May-2014-Abstract.pdf)
- [x] [2012 general](http://www.co.washington.or.us/AssessmentTaxation/Elections/ElectionsArchive/upload/abstract-11-12.pdf)
- [x] 2012 primary
- [x] [2012 special general](http://www.co.washington.or.us/AssessmentTaxation/Elections/CurrentElection/upload/Precinct-Abstract0112.pdf)
- [x] [2011 special primary](http://www.co.washington.or.us/AssessmentTaxation/Elections/upload/EL52.HTM)
- [x] [2010 general](http://www.co.washington.or.us/AssessmentTaxation/Elections/ElectionsArchive/upload/November-2010-abstract.pdf)
- [x] [2010 primary](http://www.co.washington.or.us/AssessmentTaxation/Elections/CurrentElection/upload/May-2010-Abstract.pdf)
- [x] [2008 general](http://www.co.washington.or.us/AssessmentTaxation/Elections/ElectionsArchive/upload/November-2008-Abstract.pdf)
- [x] [2008 primary](http://www.co.washington.or.us/AssessmentTaxation/Elections/ElectionsArchive/upload/May-2008-Abstract.pdf)
- [x] [2006 general](http://www.co.washington.or.us/AssessmentTaxation/Elections/ElectionsArchive/upload/November-2006-Abstract.pdf)
- [x] [2006 primary](http://www.co.washington.or.us/AssessmentTaxation/Elections/ElectionsArchive/upload/May-2006-Abstract.pdf)
- [x] [2004 general](http://www.co.washington.or.us/AssessmentTaxation/Elections/ElectionsArchive/upload/November-2004-Abstract.pdf)
- [x] [2004 primary](http://www.co.washington.or.us/AssessmentTaxation/Elections/ElectionsArchive/upload/May-2004-Abstract.pdf)
- [x] [2002 general](http://www.co.washington.or.us/AssessmentTaxation/Elections/ElectionsArchive/upload/November-2002-Abstract.pdf)
- [x] [2002 primary](http://www.co.washington.or.us/AssessmentTaxation/Elections/ElectionsArchive/upload/May-2002-Abstract.pdf)
- [x] [2000 general](http://www.co.washington.or.us/AssessmentTaxation/Elections/ElectionsArchive/upload/November-2000-Precinct-Abstract.pdf)
- [x] [2000 primary](http://www.co.washington.or.us/AssessmentTaxation/Elections/ElectionsArchive/upload/May-2000-Precinct-Abstract.pdf)

**Comment by danhillreports** [comment]
Looks like the 2011 link is a special primary, the actual special election was on January 31, 2012
http://www.co.washington.or.us/AssessmentTaxation/Elections/CurrentElection/upload/Precinct-Abstract0112.pdf

**Comment by dwillis** [comment]
Right you are - fixed that link and added the 2012 special.

**Comment by danhillreports** [comment]
2010 primary link http://www.co.washington.or.us/AssessmentTaxation/Elections/CurrentElection/upload/May-2010-Abstract.pdf

**Comment by dwillis** [comment]
Fixed, thanks!
