### ISSUE TITLE
Parse Columbia County results

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-or#98]
- [x] [2016 primary](http://www.co.columbia.or.us/files/elections/5-17_Abstract.pdf)
- [x] 2014 general
- [x] [2014 primary](http://www.co.columbia.or.us/files/elections/archive/official_canvas_may_2014.pdf)
- [x] [2012 special](http://www.co.columbia.or.us/files/elections/archive/2012-01-31_official_canvas.html)
- [x] [2012 primary](http://www.co.columbia.or.us/files/elections/archive/2012-05-15_primary_election_official_abstract.pdf)
- [x] [2012 general](http://www.co.columbia.or.us/files/elections/archive/2012-11-06_general_election_official_canvas.html)
- [x] [2010 general](http://www.co.columbia.or.us/files/elections/archive/2010-11-2_general_election_official_abstract.pdf)
- [x] [2010 primary](http://www.co.columbia.or.us/files/elections/2010-primary-results.pdf)
- [x] [2008 general](http://www.co.columbia.or.us/files/elections/november_2008_election_results_by_precinct.pdf)
- [x] [2008 primary](http://www.co.columbia.or.us/files/elections/archive/2008-5-20_primary_precinct_level_results.htm)
- [x] [2006 general](http://www.co.columbia.or.us/files/elections/archive/2006-11-7_general_election_numbered_key_canvas.html)
- [x] [2006 primary](http://www.co.columbia.or.us/files/elections/archive/2006-5-16_primary_precinct_level_results.txt)
- [x] [2004 general](http://www.co.columbia.or.us/files/elections/archive/2004-11-02_official_abstract.pdf)
- [x] [2004 primary](http://www.co.columbia.or.us/files/elections/2004-primary-results.pdf)

**Comment by nk9** [comment]
Unless I'm mistaken, the 2008 primary csv is already in 2008/. I don't see the 2008 general. [Their website](http://www.co.columbia.or.us/files/elections/archive/) doesn't seem to contain the precinct-level 2008 general results.

**Comment by dwillis** [comment]
You are correct, and I've updated this issue to reflect that. It might be worth contacting the county to see if they have 2008 general precinct results.

**Comment by nk9** [comment]
OK, I've sent an email. We'll see what comes back.

**Comment by nk9** [comment]
Found the [2008 general PDF](http://www.co.columbia.or.us/files/elections/november_2008_election_results_by_precinct.pdf) on their site, but unlinked.

**Comment by nk9** [comment]
Nit: [2014 general PDF](http://www.co.columbia.or.us/files/elections/archive/2014_general_election_abstract.pdf) is on the site and completed in git, but not included in the list above.

**Comment by nk9** [comment]
For posterity, and because it took some sleuthing to figure it out, here's the pre-2007 Columbia County [election results page](https://web-beta.archive.org/web/20020809163035/http://www.co.columbia.or.us:80/Elections/election.m.asp) on archive.org. It's pretty useless, sadly, because it doesn't keep an archive of the old results, just the last couple of elections. Also, archive.org seems not to have downloaded the pdfs at the time, which have now gone missing from the site. Ah, well…

**Comment by dwillis** [comment]
Still, that's some good sleuthing.

**Comment by nk9** [comment]
Spoke with the Columbia Co elections department to follow up my emails about getting the missing results. They are going to get back to me with info on what they have. The person I spoke to suggested it was likely that he'd need to scan the old results, as opposed to just finding them on a hard drive somewhere.

**Comment by nk9** [comment]
After one phone call and five emails, I've decided to go up a level. Just sent a request to one of the county commissioners to get the elections department to release the missing records. Will report back once I have more news…

**Comment by dwillis** [comment]
Thanks for your efforts, @nk9. I've had luck with that approach in other Oregon counties.

**Comment by nk9** [comment]
It's not fast, but it is coming. They've posted the missing [2010 primary](http://www.co.columbia.or.us/files/elections/2010-primary-results.pdf) and [2004 primary](http://www.co.columbia.or.us/files/elections/2004-primary-results.pdf) results. Still working on the 2002 and 2000 ones. That may require payment. :-(

**Comment by dwillis** [comment]
Thanks for the update. If they do require payment, let me know.

**Comment by acolter** [comment]
Working on 2008 and 2004 files.
