### ISSUE TITLE
Data Entry for Tillamook County results

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-or#99]
You can model the CSV result off the [2012 primary file](https://github.com/openelections/openelections-data-or/blob/master/2012/20120515__or__primary__tillamook__precinct.csv). Elections with multiple files go in the same single CSV file.

- [x] [2016 primary](https://github.com/openelections/openelections-sources-or/blob/master/Tillamook/May%2017%202016%20Abstract.pdf)
- [x] 2014 general [part 1](https://github.com/openelections/openelections-sources-or/blob/master/Tillamook/November%2019%202014%20Part%201.pdf) and [part 2](https://github.com/openelections/openelections-sources-or/blob/master/Tillamook/November%2019%202014%20Part%202.pdf)
- [x] [2014 primary](https://github.com/openelections/openelections-sources-or/blob/master/Tillamook/May%2020%202014.pdf)
- [x] 2012 general [part 1](https://github.com/openelections/openelections-sources-or/blob/master/Tillamook/November%206%202012%20Part%201.pdf) and [part 2](https://github.com/openelections/openelections-sources-or/blob/master/Tillamook/November%206%202012%20Part%202.pdf)
- [x] 2010 general [part 1](https://github.com/openelections/openelections-sources-or/blob/master/Tillamook/November%202%202010%20Part%201.pdf) and [part 2](https://github.com/openelections/openelections-sources-or/blob/master/Tillamook/November%202%202010%20Part%202.pdf)
- [x] 2010 primary [part 1](https://github.com/openelections/openelections-sources-or/blob/master/Tillamook/May%2018%202010%20Part%201.pdf) and [part 2](https://github.com/openelections/openelections-sources-or/blob/master/Tillamook/May%2018%202010%20Part%202.pdf)

**Comment by elliottmorris** [comment]
Will start on 2010 general part 1

**Comment by dwillis** [comment]
Thanks!

**Comment by dwillis** [comment]
@elliottmorris: any luck with 2010 general?

**Comment by elliottmorris** [comment]
Hey, distracted by work, feel free to work on it. Much left unfortunately

**Comment by dwillis** [comment]
No worries, thanks!

**Comment by nk9** [comment]
Requested 2000–2008 results. We'll see what they say.

**Comment by dwillis** [comment]
They will say "pay us a lot of money"

**Comment by nk9** [comment]
"The fee to get all of the abstracts that you have requested would be $197.25.  You can make the check payable to the “Tillamook County Clerk” and mail it to the address below.  Thank you and I hope you are having a great day!"

LOOOOOOL!

**Comment by elliottmorris** [comment]
Better just to ask the 400lb hacker to get them for us

**Comment by dwillis** [comment]
She's consistent, I'll say that for Ms. O'Neil.
